Add custom path system
Vankka/DependencyDownload pull request #6
Opened 2022-01-12 16:31 UTC by Romaindu35

This pull request add support to use custom path system

2022-01-17 13:11 UTC, Vankka requested changes
I think the `CustomPath` class should be called `DependencyPathProvider`.

Also since `DependencyManager`s are meant to be "single use" there could be another constructor that just takes a path provider instead of a `Path`, and the provider would become immutable (`final` field and setter removed).

I've also left some wording, annotation and code comments below (The suggestions are missing imports, please check those if you decide to apply the suggestions)

2022-01-17 13:11 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/DependencyManager.java
> +    }
```suggestion
    /**
     * Gets the custom path provider for this DependencyManager.
     * @return the instance of CustomPath or {@code null}
     * @see CustomPath
     */
    @Nullable
    public CustomPath getCustomPath() {
        return customPath;
    }
```

2022-01-17 13:11 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/DependencyManager.java
> +    }
```suggestion
    /**
     * Sets the custom path provider for this DependencyManager.
     * @param customPath the new path provider
     * @see CustomPath
     */
    public void setCustomPath(@Nullable CustomPath customPath) {
        this.customPath = customPath;
    }
```

2022-01-17 13:11 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/DependencyManager.java
> +    }
```suggestion
    /**
     * Gets if a custom path provider is set.
     * @return {@code true} if a custom path provider is set, otherwise {@code false}
     * @see CustomPath
     */
    public boolean hasCustomPath() {
        return this.customPath != null;
    }
```

2022-01-17 13:11 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/DependencyManager.java
> +            return getCustomPath().getCustomPath(dependency);
```suggestion
        if (hasCustomPath()) {
            return getCustomPath().getCustomPath(dependency);
        }
```

2022-01-17 13:11 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/DependencyManager.java
> +            Files.createDirectories(dependencyPath.getParent());
```suggestion
        if (!Files.exists(dependencyPath.getParent())) {
            Files.createDirectories(dependencyPath.getParent());
        }
```

2022-01-17 13:11 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/path/CustomPath.java
> +public interface CustomPath {
```suggestion
/**
 * A {@link Path} provider for {@link Dependency Dependencies}.
 */
@FunctionalInterface
public interface CustomPath {
```

2022-01-17 13:11 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/path/CustomPath.java
> +    Path getCustomPath(Dependency dependency);
```suggestion
    /**
     * Gets the path that should be used for the provided {@link Dependency}.
     * @param dependency the dependency
     * @return The absolute or relative path for the provided dependency
     */
    @NotNull
    Path getCustomPath(@NotNull Dependency dependency);
```

2022-01-17 14:58 UTC, Vankka commented
Another thought I had, maybe the interface should have another parameter, `boolean relocated` to determine relocated paths

2022-01-18 18:28 UTC, Romaindu35 commented
What do you mean by "Also since DependencyManagers are meant to be "single use" there could be another constructor that just takes a path provider instead of a Path, and the provider would become immutable (final field and setter removed)." ?
Make DependencyPathProvider with constructor, getter, and setter and add a field of AbstractDependencyPathProvider that it is functionnal interface ?

2022-01-18 18:52 UTC, Vankka commented
What I meant is that DependencyManager could be constructed with Path **or** DependencyPathProvider so instead of needing to do 
```java
DependencyManager manager = new DependencyManager(Paths.get("."));
manager.setDependencyPathProvider(new DependencyPathProviderImpl());
```
you would be able to do
```java
DependencyManager manager = new DependencyManager(new DependencyPathProviderImpl());
```
(Use `DependencyPathProvider` directly in the constructor of DependencyManager). Then the `dependencyPathProvider` field should be final and `setDependencyPathProvider` should be removed. Sorry if it's hard to understand

2022-01-18 19:35 UTC, Romaindu35 commented
Ok, I understand, but what is bester:
Modify actual constructor, or add two option ?
Else, I don't know if it is bester to make an default DependencyPathProvider, so this prevent null, and can be more optimized when we get file path. (A static field in DependencyPathProvider class)

2022-01-18 21:53 UTC, Vankka commented
Two constructors would be the ideal way, either the path provider or a path should be available at any given time

2022-01-19 10:35 UTC, Romaindu35 commented
I have add constructor and modify actual to always use DependencyPathProvider, but I don't know how I can apply function cleanupCacheDirectory. Are you and idea ?

2022-01-20 10:42 UTC, Vankka commented
I'd propose something like this,

Make a implementation of `DependencyPathProvider` that takes in a `Path` (and use it in the constructor taking in a path)
```java
public class DirectoryDependencyPathProvider implements DependencyPathProvider {
    
    private static final String RELOCATED_FILE_PREFIX = "relocated_";
    private final Path cacheDirectory;
    
    public DirectoryDependencyPathProvider(Path cacheDirectory) {
        this.cacheDirectory = cacheDirectory;
    }

    @Override
    public Path getDependencyPathProvider(Dependency dependency, boolean relocated) {
        return cacheDirectory.resolve((relocated ? RELOCATED_FILE_PREFIX : "") + dependency.getStoredFileName())
    }

    public Path getCacheDirectory() {
         return cacheDirectory;
    }
}
```
and in cleanup cache directory method do something like
```java
if (!(pathProvider instanceof DirectoryDependencyPathProvider)) {
    // Not sure if "static directory" is the best wording here
    throw new IllegalStateException("Cache directory cleanup is only available when using a static directory"); 
} 
Path = ((DirectoryDependencyPathProvider) pathProvider).getCacheDirectory();
...
```
(Remember to add the exception to the javadoc and explain that the constructor that uses Path needs to be used)

2022-01-20 20:42 UTC, Romaindu35 commented
I think it is better if we create new interface named CleanupPathProvider that implement DependencyPathProvider with new abstract method named getCleanupPathProvider.
DirectoryDependencyPathProvider will be implemnt CleanupPathProvider. 
With this sytem, users can make system compatible with cleanupCache system if they implement CleanupPathProvider and not DependencyPathProvider

2022-01-20 22:55 UTC, Vankka commented
I'm fine with that

2022-01-21 15:11 UTC, Romaindu35 commented
I think it is good

2022-01-24 11:07 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/path/DependencyPathProvider.java
> +    Path getDependencyPathProvider(@NotNull Dependency dependency, boolean relocated);
```suggestion
    /**
     * Gets the path that should be used for the provided {@link Dependency}.
     * @param dependency the dependency
     * @param relocated if the path should be for the relocated or unrelocated file
     * @return The absolute or relative path for the provided dependency
     */
    @NotNull
    Path getDependencyPath(@NotNull Dependency dependency, boolean relocated);
```

2022-01-24 11:07 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/path/CleanupPathProvider.java
> +    Path getCleanupPathProvider();
```suggestion
    /**
     * Gets the path that should be used for removing unused files using {@link dev.vankka.dependencydownload.DependencyManager#cleanupCacheDirectory}.
     * @return The absolute or relative path use for cleanup directory (should be the directory where the dependencies are stored)
     */
    @NotNull
    Path getCleanupPath();
```

2022-01-24 11:07 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/DependencyManager.java
> +     * @param relocated: true if it is a relocated dependency
```suggestion
     * @param relocated if the path should be for the relocated or unrelocated file of the Dependency
```

2022-01-24 11:07 UTC, Vankka commented on runtime/src/main/java/dev/vankka/dependencydownload/DependencyManager.java
>       */
```suggestion
     * @throws IOException if listing files in the cache directory or deleting files in it fails
     * @throws IllegalStateException if this DependencyManager's dependencyPathProvider isn't a instance of {@link CleanupPathProvider}
     * @see #getAllPaths(boolean)
     * @see CleanupPathProvider
     */
```

2022-01-27 16:35 UTC, Vankka approved these changes

2022-01-27 16:35 UTC, merged